# (prenom, nom, entreprise, domaine, poste, pays, secteur, origine, email_force, note)
C=[
# --- Relances lot 2 : prenom.nom@ rejeté (serveur qui répond), on passe à prenom@
("Mo","Abudu","EbonyLife Media","ebonylifemedia.com","CEO","Nigeria","Fiction","relance lot 2 (mo.abudu@ inexploitable)",None,"Agrégateur annonçait initiale+nom@ : variante mabudu@"),
("Rudi","van As","Film Afrika","filmafrika.com","CEO","South Africa","Fiction","relance lot 2 (rudi.vanas@ inexploitable)",None,""),
("Eugene","Mbugua","D&R Studios","dnrstudios.co.ke","Founder & CEO","Kenya","Fiction","relance lot 2 (eugene.mbugua@ inexploitable)",None,""),
("Jide","Martin","Comic Republic (CR Motion+)","thecomicrepublic.com","Founder & CEO","Nigeria","Animation","relance lot 2 (jide.martin@ inexploitable)",None,"Agrégateur annonçait jidemartin@ : variante"),
("Mathew","Nabwiso","Nabwiso Films","nabwisofilms.com","Founder & Managing Director","Uganda","Fiction","relance lot 2 (mathew.nabwiso@ inexploitable)",None,"ZoomInfo masque m***@"),
("Eleanor","Nabwiso","Nabwiso Films","nabwisofilms.com","Co-founder & Creative Director","Uganda","Fiction","relance lot 2 (eleanor.nabwiso@ inexploitable)",None,"Même maison que Mathew : à séquencer"),
("Benon","Mugumbya","Swangz Avenue","swangzavenue.com","Founder","Uganda","Pub/doc","relance lot 2 (benon.mugumbya@ inexploitable)",None,""),
("Richard","Oboh","Orange VFX Studios","orangevfx.com","Founder & CEO","Nigeria","Animation","relance lot 2 (richard.oboh@ inexploitable)",None,"ZoomInfo masque r***@, cohérent avec richard@"),
("Adebisi","Adetayo","32ad Animation Studios","32ad.com.ng","Co-founder & Technical Director","Nigeria","Animation","relance lot 2 (adebisi.adetayo@ inexploitable)","bisi@32ad.com.ng","Connu sous le nom « Bisi » (africanfilmny.org/directors/bisi-adetayo) ; variante adebisi@"),
("Rehad","Desai","Uhuru Productions","uhuruproductions.co.za","Founder","South Africa","Pub/doc","relance lot 2 (rehad@ inexploitable)","rdesai@uhuruproductions.co.za","prenom@ déjà rejeté : variante initiale+nom@"),
("Sanaa","Mothabisa","Sanaa Films","sanaafilms.com","Founder & Director","South Africa","Pub/doc","relance lot 2 (sanaa@ inexploitable)","smothabisa@sanaafilms.com","prenom@ déjà rejeté : variante initiale+nom@"),
("Philbert Aimé","Mbabazi Sharangabo","Imitana Productions","imitana.com","Co-founder & Producer","Rwanda","Fiction","relance lot 2 (philbert@ inexploitable)","pmbabazi@imitana.com","prenom@ déjà rejeté : variante initiale+nom@"),
# --- Écartés lots 2-3 avec nom et domaine (rejetés surtout faute de 2e source datée)
("Uche","Anisiuba","Quadron Studios","quadronstudios.com","CEO","Nigeria","Animation","écarté lot 2 (pas de source 2025-2026)",None,""),
("Jadesola","Osiberu","Greoh Studios","greoh.com","Founder","Nigeria","Fiction","écarté lot 2 (activité 2025-2026 non confirmée)",None,"Connue sous le nom Jáde Osiberu"),
("Tope","Oshin","Sunbow Productions","sunbowproductions.com","Founder","Nigeria","Fiction","écarté lot 2 (domaine non confirmé)",None,""),
("Jay","Jituboh","Trino Studios","trinostudios.com","Founder","Nigeria","Fiction","écarté lot 2 (lien personne/structure non confirmé)",None,"Jay Franklyn Jituboh"),
("Nissi","Ogulu","Creele Animation Studios","creelestudios.com","Founder","Nigeria","Animation","écarté lot 2 (structure créée en 2025)",None,""),
("Richard","Morgan-Grenville","Strika Entertainment (Supa Strikas)","supastrikas.com","CEO","South Africa","Animation","écarté lot 2 (pas de source 2025-2026)",None,""),
("Christian","van der Walt","Sinister Studio","sinisterstudio.co.za","Owner","South Africa","Animation","écarté lot 2 (pas de source 2025-2026)",None,""),
("Chris","Heaton","The Refinery","therefinery.co.za","Managing Director","South Africa","Animation","écarté lot 2 (pas de source 2025-2026)",None,"Surtout post-production"),
("Tim","Argall","Bugbox Animation","bugbox.co.za","Owner","South Africa","Animation","écarté lot 2 (pas de source 2025-2026)",None,""),
("Nic","Buchanan","Pixcomm","pixcomm.co.za","Owner","South Africa","Animation","écarté lot 2 (pas d'activité 2025-2026)","nic@pixcomm.co.za","Email vu dans un extrait de recherche (publié)"),
("David","Ferreira","Golden Road Entertainment","goldenroad.tv","Founder","South Africa","Animation","écarté lot 2 (pas de source 2025-2026)","david@goldenroad.tv","Email vu dans un extrait de recherche (publié)"),
("Mfundi","Vundla","Morula Pictures","morula.co.za","Chairman","South Africa","Fiction","écarté lot 2 (hors lot animation)",None,""),
("Leanne","Kumalo","Seriti Films","seriti.tv","Managing Director","South Africa","Fiction","écarté lot 2 (pas de source 2025-2026)",None,""),
("Connie","Ferguson","Ferguson Films","fergusonfilms.co.za","Co-founder","South Africa","Fiction","écarté lot 2 (rôle non confirmé 2025-2026)",None,""),
("Michael","Auret","Spier Films","spierfilms.com","Managing Director","South Africa","Fiction","écarté lot 2 (pas d'activité 2025-2026)",None,""),
("Janette","de Villiers","Groundglass","groundglass.co.za","Founder & Executive Producer","South Africa","Pub/doc","écarté lot 2 (pas de source 2025-2026)",None,""),
("Diana","Keam","Silver Bullet Films","silverbullet.co.za","Co-owner","South Africa","Pub/doc","écarté lot 2 (pas de source 2025-2026)",None,""),
("Basetsana","Kumalo","Tswelopele Productions","tswelopele.co.za","Executive Chairperson","South Africa","Pub/doc","écarté lot 2 (mêmes propriétaires que Cardova)",None,"À séquencer avec Patience Stevens (Cardova)"),
("Noah","Okeyo","Selene Studios","selenestudios.co.ke","CEO","Kenya","Pub/doc","écarté lot 2 (hors lot animation)",None,""),
("Nick","Mutuma","Giraffe Africa Productions","shotbygiraffe.com","Founder","Kenya","Fiction","écarté lot 2 (domaine principal sans MX)",None,"Domaine alternatif shotbygiraffe.com"),
("Cyril","Ofori","So Fraiche Media","sofraiche.com","Managing Director & Co-founder","Ghana","Pub/doc","écarté lot 2 (siège à Londres)",None,""),
("Sarah","Dowuona","Film Etoile","filmetoile.com","Co-founder","Ghana","Fiction","écarté lot 2 (pas de 2e source datée)",None,""),
("Akontam","Issah","Starling Media Ghana","smediagh.online","Founder","Ghana","Pub/doc","écarté lot 2 (sources annuaires)",None,""),
("Esther","Ohrt Paul","Afrotoons","afrotoons.com","Co-founder & CEO","Ghana","Animation","écarté lot 2 (lancé en mai 2026)",None,""),
("Ahmed","Bahar","Masarib","masarib.rw","Founder","Rwanda","Pub/doc","écarté lot 2 (dirigeant non confirmé)",None,""),
("David","Sevuri","True Vision Production","truevision.co.tz","Managing Director","Tanzania","Pub/doc","écarté lot 2 (pas de source 2025-2026)",None,""),
("Joe","Njagu","Area 46 Productions","area46.co.zw","Managing Director","Zimbabwe","Fiction","écarté lot 2 (une seule source)",None,"Agrégateur annonçait prenom.nom@"),
("Kalai","Barlow","Obscura Films","obscurafilms.studio","Director/Producer","Tanzania","Fiction","écarté lot 2 (pas de source 2025-2026)",None,""),
("John","Riber","Media for Development International","mfditanzania.com","Founder & Director","Tanzania","Fiction","écarté lot 2 (pas de source 2025-2026)",None,""),
("Cait","Pansegrouw","Urucu Media","urucumedia.com","Producer","South Africa","Fiction","écarté lot 3 (2e contact de la maison)",None,"À séquencer après Elias Ribeiro"),
("Roberta","Durrant","Penguin Films","penguinfilms.co.za","Founder","South Africa","Fiction","écarté lot 3 (pas de source 2025-2026)",None,""),
("Kethiwe","Ngcobi","Fuzebox Entertainment","fuzebox.co.za","CEO & Founder","South Africa","Pub/doc","écarté lot 3 (une seule source)",None,""),
("Helena","Woodfine","Romance Films","romancefilms.tv","Executive Producer","South Africa","Pub/doc","écarté lot 3 (pas de source 2025-2026)",None,""),
("Cindy","Gabriel","Giant Films","giantfilms.tv","Managing Partner","South Africa","Pub/doc","écarté lot 3 (une seule source)",None,"À séquencer après Emma Lundy"),
("Joan","Kabugu","Ecila Films","ecilafilms.com","Managing Director","Kenya","Fiction","écarté lot 3 (pas de source 2025-2026)",None,""),
("Remy","Ryumugabe","KIRURI MFN","kirurimfn.com","Co-founder","Rwanda","Fiction","écarté lot 3 (pas de source 2025-2026)","ryumugabe@kirurimfn.com","Email publié (vu dans un extrait de recherche)"),
("Nqobizitha","Mlilo","NafunaTV","nafuna.tv","Founder","Zimbabwe","Pub/doc","écarté lot 3 (pas de source 2025-2026)",None,""),
("Shaun","Chitsiga","Bizani Media Productions","bizani.co.zw","Contact","Zimbabwe","Pub/doc","écarté lot 3 (rôle non établi)",None,""),
("Michael","Muthiga","FatBoy Animations","fatboyanimations.com","Founder","Kenya","Animation","lot 3 sans email (domaine non confirmé)",None,""),
("Moses","Babatope","Nile Media Entertainment Group","nilemediagroup.com","CEO","Nigeria","Fiction","lot 3 sans email (domaine non confirmé)",None,""),
]
